# Generated by Django 4.2 on 2026-05-30 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial (some errors)'), ('failed', 'Failed')], db_index=True, default='running', max_length=10)),
                ('scraped_count', models.PositiveIntegerField(default=0, help_text='Articles returned by scraper')),
                ('new_count', models.PositiveIntegerField(default=0, help_text='New records inserted')),
                ('skipped_count', models.PositiveIntegerField(default=0, help_text='Duplicates skipped')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Records that failed processing')),
                ('error_detail', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
