# Generated by Django 4.2 on 2026-05-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(max_length=2000)),
                ('source', models.CharField(db_index=True, help_text='Provider name, e.g. rekt.news', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='False until analytics has cleaned this record.')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Original publication date from the source.', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='reports', to='reports.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hackreport',
            index=models.Index(fields=['title'], name='reports_hac_title_9aea08_idx'),
        ),
        migrations.AddIndex(
            model_name='hackreport',
            index=models.Index(fields=['severity'], name='reports_hac_severit_f964f8_idx'),
        ),
        migrations.AddIndex(
            model_name='hackreport',
            index=models.Index(fields=['created_at'], name='reports_hac_created_a91464_idx'),
        ),
        migrations.AddIndex(
            model_name='hackreport',
            index=models.Index(fields=['published_at'], name='reports_hac_publish_118b20_idx'),
        ),
        migrations.AddIndex(
            model_name='hackreport',
            index=models.Index(fields=['source'], name='reports_hac_source_072a24_idx'),
        ),
    ]
