# Generated by Django 4.2 on 2026-05-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackreport',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
