# Generated by Django 4.2 on 2026-05-30 19:55

from django.db import migrations
import pgvector.django.vector
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='hackreport',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
